name: Restrict PRs to master branch

on:
  pull_request:
    branches:
      - master

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from release
        if: github.head_ref != 'release'
        run: |
          echo "❌ Pull requests to master must come from release"
          exit 1
